### ISSUE TITLE
Question on Training / Evaluation Data

### ISSUE THREAD

**Issue by kirkins** [microsoft/presidio-research#12]
Hello again, in the [last issue I opened](https://github.com/microsoft/presidio-research/issues/7), you mentioned for training Flair we might want to use our own data.

This seems to be good advice to me as I've realized that there are only 125 templates included in the data generator. Thus the 300 samples used for training the model, and the 300 samples used in evaluation inevitably include many near duplicates for example:

    The name in the account is not correct, please change it to Philip Jessen

    The name in the account is not correct, please change it to Alexandra Dalgety

I believe this large overlap in data invalidates the evaluation scores for the custom trained Flair and SpaCey models which use it _(for example we have one Flair model which scores over 98.5% which seems too high)_. 

My colleague is convinced that because this data was included as the default in a Microsoft repository that it must be ok to use as is.

Could you help me to confirm what I'm thinking? That we need to use our own data or add more templates, if we want to accurately assess our trained models.

**Comment by omri374** [comment]
Hi,
125 templates are obviously not enough. These models should pick up entities given variance in natural language around them, and using a small set of templates would cause the model to memorize the templates rather then generalizing and learning how entities appear in sentences.
The 125 templates are just there for reference.

In one of the analyses, we downloaded a big NER dataset (OntoNotes or CONLL) and used the sentences there to create a new set of templates. This (after manual cleansing) provided us with more than 10k templates.

Another thing to verify, is that the same template does not appear in both train and test, because that would let you choose models which are memorizing templates instead of models that learn entity representations.
The repo has some support for this. If you need more guidance, feel free to reach out.

**Comment by kirkins** [comment]
That's a huge help. I wasn't aware of the scripts/notebooks for generating more templates. I was able to figure out and we're now using a much bigger data-set.

Thanks again.
